### ISSUE TITLE
go install - invalid version: unknown revision

### ISSUE THREAD

**Issue by lipoja** [release-engineering/dcm#2]
I was not able to install `dcm` when I followed the instruction in README.md because some reference in `go.mod` file does not exist. 

`go: github.com/joelanford/operator-registry@v1.12.2-0.20210611160053-babcf9d97125: invalid version: unknown revision babcf9d97125`

**Comment by joelanford** [comment]
I'll take a look!

**Comment by joelanford** [comment]
@lipoja I pushed two fixes:
1. It looks like it may be that your local GOPROXY environment variable needs to be set to include a proxy that has a copy of that commit. I updated the install instructions to specify a GOPROXY value that should work.
2. I updated the replace value in `go.mod` to point to a commit that's the current head of my fork's branch, so fix 1 should not be necessary (for right now at least)

**Comment by lipoja** [comment]
@joelanford Thanks, it fixed the issue however I run into another one. 
```bash
GOPROXY="https://proxy.golang.org|direct" go install .
../../go/pkg/mod/github.com/joelanford/ignore@v0.0.0-20210607151042-0d25dc18b62d/ignore.go:5:2: package io/fs is not in GOROOT (/usr/lib/golang/src/io/fs)
```
I am sorry but do not have any experience with Golang. Could you help me with this one as well?

**Comment by joelanford** [comment]
No worries! That error is likely because you're using a version of Go that does not contain io/fs in the standard library. Make sure you're using at least Go 1.16.

**Comment by joelanford** [comment]
As an aside, once I have some time to work on #1, you'll be able to just download binaries from the releases page and won't even have to have Go installed on your system.

**Comment by lipoja** [comment]
I've set Golang 1.16.6 `go version go1.16.6 linux/amd64` it passed but I guess I miss something else.

```# github.com/release-engineering/dcm/action
action/add.go:112:29: imageInput.AnnotationsFile undefined (type *registry.ImageInput has no field or method AnnotationsFile)
```

Note: I wanted to run it and see what `dcm` supports and what needs to be installed to replace `opm` in IIB.

**Comment by joelanford** [comment]
~Ah yes, I'm seeing this now too. Working on a fix now!~

Done!

**Comment by joelanford** [comment]
I was able to get some release automation working, so you should be able to download releases directly from here: https://github.com/release-engineering/dcm/releases

**Comment by joelanford** [comment]
Closing this as I think all the issues you were running into should be solved now!
